{% set name = "resolvelib" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # GitHub release contains tests/
  url: https://github.com/sarugaku/{{ name|lower }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 660e2cef5342adfcdf2144539b4bfcba660682db3a8f3feb31d9ff153af8c461

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - resolvelib
  requires:
    - pip
    - packaging
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/sarugaku/resolvelib
  license: ISC
  license_file: LICENSE
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    ResolveLib at the highest level provides a Resolver class that
    includes dependency resolution logic. You give it some things, and a
    little information on how it should interact with them, and it will
    spit out a resolution result.
  doc_url: https://github.com/sarugaku/resolvelib/blob/master/README.rst
  dev_url: https://github.com/sarugaku/resolvelib

extra:
  recipe-maintainers:
    - etcet
