{% set name = "resolvelib" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # GitHub release contains tests/
  url: https://github.com/sarugaku/{{ name|lower }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 01af9b4de4f417a69479bbaa45d7b49baefe33897c27d76cbb79a43f9a2e0bf0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - resolvelib
  requires:
    - pip
    - pytest
    - commentjson
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/sarugaku/resolvelib
  license: ISC
  license_file: LICENSE
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    ResolveLib at the highest level provides a Resolver class that
    includes dependency resolution logic. You give it some things, and a
    little information on how it should interact with them, and it will
    spit out a resolution result.
  doc_url: https://github.com/sarugaku/resolvelib/blob/master/README.rst
  dev_url: https://github.com/sarugaku/resolvelib

extra:
  recipe-maintainers:
    - etcet
